//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iw4x_launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iw4x_launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define ITEM_MENU_TITLE_VIS(textArg, visArg) \
        ///	itemDef \
        ///	{ \
        ///		rect														-50 -35 146 28 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP \
        ///		foreColor													CHOICE_TEXTCOLOR \
        ///		textFont													9 \
        ///		textScale													0.45 \
        ///		decoration													\
        ///		textAlign													ITEM_ALIGN_MIDDLE_LEFT \
        ///		text														textArg \
        ///		textAlignX													5 \
        ///		visible														visArg \
        ///	}
        ///
        ///#define BUTTON_FOOTER(xPos, width, buttonName, textArg, actionArg) \
        ///		BUTTON_FOOTER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string joinserver_6 {
            get {
                return ResourceManager.GetString("joinserver_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define ITEM_MENU_TITLE_VIS(textArg, visArg) \
        ///	itemDef \
        ///	{ \
        ///		rect														-50 -35 146 28 HORIZONTAL_ALIGN_LEFT VERTICAL_ALIGN_TOP \
        ///		foreColor													CHOICE_TEXTCOLOR \
        ///		textFont													9 \
        ///		textScale													0.45 \
        ///		decoration													\
        ///		textAlign													ITEM_ALIGN_MIDDLE_LEFT \
        ///		text														textArg \
        ///		textAlignX													5 \
        ///		visible														visArg \
        ///	}
        ///
        ///#define BUTTON_FOOTER(xPos, width, buttonName, textArg, actionArg) \
        ///		BUTTON_FOOTER_VIS(xPos, widt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string joinserver_7 {
            get {
                return ResourceManager.GetString("joinserver_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp_afghan            Afghan 
        ///mp_derail            Derail 
        ///mp_estate            Estate 
        ///mp_favela            Favela 
        ///mp_highrise          Highrise 
        ///mp_invasion          Invasion 
        ///mp_checkpoint        Karachi 
        ///mp_quarry            Quarry 
        ///mp_rundown           Rundown 
        ///mp_rust              Rust 
        ///mp_boneyard          Scrapyard 
        ///mp_nightshift        Skidrow 
        ///mp_subbase           Sub Base 
        ///mp_terminal          Terminal 
        ///mp_underpass         Underpass 
        ///mp_brecourt          Wasteland
        ///mp_complex      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resource_String_Maps {
            get {
                return ResourceManager.GetString("Resource_String_Maps", resourceCulture);
            }
        }
    }
}
